# Generated by Django 5.0.7 on 2024-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodic",
            field=models.IntegerField(
                choices=[
                    (1, "Ежедневно"),
                    (2, "Каждые 2 дня"),
                    (3, "Каждые 3 дня"),
                    (4, "Каждые 4 дня"),
                    (5, "Каждые 5 дней"),
                    (6, "Каждые 6 дней"),
                    (7, "Еженедельно"),
                ],
                default=1,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Место выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время выполнения привычки"
            ),
        ),
    ]
