# Generated by Django 5.0.7 on 2024-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_periodic_alter_habit_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя отправка"
            ),
        ),
    ]
